### ISSUE TITLE
possible crash caused by VP ?

### ISSUE THREAD

**Issue by TheRanker** [PydingAbsorber/VestigesOfThePresent#2]
[crash-2024-05-11_13.52.14-server.txt](https://github.com/PydingAbsorber/VestigesOfThePresent/files/15283036/crash-2024-05-11_13.52.14-server.txt)

brand n ew world. exploring for a bit.. then hard server crash.  and will not boot back up .. same crash again. 

unsure if this is from your mod or not, but it is a suspected mod.  

if you can verify or check it out, and get back to me i can investigate further 

thanks :)

**Comment by TheRanker** [comment]
forge 1.20.1.  not the latest update of the mod btw... one sec ill get version

**Comment by PydingAbsorber** [comment]
is it on 1.1.10 version?
