### ISSUE TITLE
Warden heals with hard mode off


### ISSUE THREAD

**Issue by TheRanker** [PydingAbsorber/VestigesOfThePresent#3]
Using the latest version of vop on latest version of forge 1.20.1. 

Disabling hard mode. 

Warden is proper health and shield but he heals like a mad man. 

Disabling VoP and warden is normal again. 

Is this a bug or something that's implemented but not documented?

**Comment by demanzke** [comment]
Some more details:

- v1.1.9 and v1.1.10 have been tested
- It has been confirmed that the hardcore = false toggle was applied (Warden armor and health returned to default)
- These settings have to be changed additionally, to make the Warden killable:

absorbHardcore = 0.0
#Hardcore mode Shield from hp percent 1 is 100%
#Range: 1.0 ~ 2.1E9
healPercent = 0.0
#Base Martyr's Habergeon(armor) value
#Range: > 0

**Comment by PydingAbsorber** [comment]
Fixed in the next update
