### ISSUE TITLE
Hardcore mode always enabled & Sniffers cannot spawn

### ISSUE THREAD

**Issue by Kingdemonic666** [PydingAbsorber/VestigesOfThePresent#4]
Minecraft Version: 1.20.1
Forge Version: 47.3.6
Mods: curios-forge-5.9.1+1.20.1 & Vestiges of the Present 1.20.1 v1.2.1

As the title says when creating a new world or joining an existing one the Hardcore mode will be active by default and it's effects will remain even if you use the /vestiges enableHardcore command.
The other issue is also self explanatory, when the mod is installed Sniffers will be unable to spawn, even if you use a spawn egg or use the summon command they won't appear and the log will be flooded with a packet error instead, this issue is present ever since v1.1.11

**Comment by PydingAbsorber** [comment]
Let me know if it's still relevant

**Comment by Kingdemonic666** [comment]
Alright, I just tried Vestiges of the Present 1.20.1 v1.2.2 with the same Minecraft, Forge & Curios version as before.
Both issues still remain in this update and behave in the same way as previously described.

**Comment by PydingAbsorber** [comment]
Thanks for noticing, I will fix those a bit later

**Comment by PydingAbsorber** [comment]
fixed(release later)
