### ISSUE TITLE
Bosses with Shield, Extra HP & Armor

### ISSUE THREAD

**Issue by Explode007** [PydingAbsorber/VestigesOfThePresent#5]
Hello!

I'm not sure if this is an intended feature, but every boss has like double their health and the overshield thing even when hardcore is disabled in the configs. Please let me know if this is intended and if you could add a feature to disable them entirely or after an advancement.

**Comment by PydingAbsorber** [comment]
Hi! It should be fixed in the latest version or in the version i'm not releasing like a month or smth
